// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDAvC1zMJQrqz1b0Nrce2N1VXSDCC7F9IE',
    appId: '1:960601389415:web:93549837c70501e892d7c2',
    messagingSenderId: '960601389415',
    projectId: 'flutter-music-app-4d51f',
    authDomain: 'flutter-music-app-4d51f.firebaseapp.com',
    storageBucket: 'flutter-music-app-4d51f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCkimTAOE6xHKjEL9EW53CFOziiw1UhmQ8',
    appId: '1:960601389415:android:d17a11086a05001b92d7c2',
    messagingSenderId: '960601389415',
    projectId: 'flutter-music-app-4d51f',
    storageBucket: 'flutter-music-app-4d51f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4HBkpsS7L77UKWGpMhKQvfnuOnACI2j4',
    appId: '1:960601389415:ios:8ca7c6e51c1e843e92d7c2',
    messagingSenderId: '960601389415',
    projectId: 'flutter-music-app-4d51f',
    storageBucket: 'flutter-music-app-4d51f.firebasestorage.app',
    iosBundleId: 'com.example.myMusicPlayer',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4HBkpsS7L77UKWGpMhKQvfnuOnACI2j4',
    appId: '1:960601389415:ios:8ca7c6e51c1e843e92d7c2',
    messagingSenderId: '960601389415',
    projectId: 'flutter-music-app-4d51f',
    storageBucket: 'flutter-music-app-4d51f.firebasestorage.app',
    iosBundleId: 'com.example.myMusicPlayer',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDAvC1zMJQrqz1b0Nrce2N1VXSDCC7F9IE',
    appId: '1:960601389415:web:79de4721731bdc6892d7c2',
    messagingSenderId: '960601389415',
    projectId: 'flutter-music-app-4d51f',
    authDomain: 'flutter-music-app-4d51f.firebaseapp.com',
    storageBucket: 'flutter-music-app-4d51f.firebasestorage.app',
  );
}
